<a href="https://colab.research.google.com/github/fabianpestchankerMMD/MMD/blob/main/hongos_(3).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder

La siguiente sección de código se incluyó por si quieren leer el archivo "mushrooms.csv" desde el disco de su PC

In [2]:
# Ejecutar para subir un archivo de datos desde su PC

from google.colab import files
file = files.upload()

Saving mushrooms.csv to mushrooms.csv

Puedo descargar directamente de un sitio Web

In [4]:
#datos=pd.read_csv("https://www.wolframcloud.com/obj/d0c0084e-0b60-46db-a4d9-beb33412905e")
#datos.head(10)
datos=pd.read_csv("mushrooms.csv")
datos.head(10)

,type,cap_shape,cap_surface,cap_color,bruises,odor,gill_attachment,gill_spacing,gill_size,gill_color,...,stalk_surface_below_ring,stalk_color_above_ring,stalk_color_below_ring,veil_type,veil_color,ring_number,ring_type,spore_print_color,population,habitat
0,poisonous,convex,smooth,brown,yes,pungent,free,close,narrow,black,...,smooth,white,white,partial,white,one,pendant,black,scattered,urban
1,edible,convex,smooth,yellow,yes,almond,free,close,broad,black,...,smooth,white,white,partial,white,one,pendant,brown,numerous,grasses
2,edible,bell,smooth,white,yes,anise,free,close,broad,brown,...,smooth,white,white,partial,white,one,pendant,brown,numerous,meadows
3,poisonous,convex,scaly,white,yes,pungent,free,close,narrow,brown,...,smooth,white,white,partial,white,one,pendant,black,scattered,urban
4,edible,convex,smooth,gray,no,none,free,crowded,broad,black,...,smooth,white,white,partial,white,one,evanescent,brown,abundant,grasses
5,edible,convex,scaly,yellow,yes,almond,free,close,broad,brown,...,smooth,white,white,partial,white,one,pendant,black,numerous,grasses
6,edible,bell,smooth,white,yes,almond,free,close,broad,gray,...,smooth,white,white,partial,white,one,pendant,black,numerous,meadows
7,edible,bell,scaly,white,yes,anise,free,close,broad,brown,...,smooth,white,white,partial,white,one,pendant,brown,scattered,meadows
8,poisonous,convex,scaly,white,yes,pungent,free,close,narrow,pink,...,smooth,white,white,partial,white,one,pendant,black,several,grasses
9,edible,bell,smooth,yellow,yes,almond,free,close,broad,gray,...,smooth,white,white,partial,white,one,pendant,black,scattered,meadows

Convierto las etiquetas en numeros

In [5]:
encoder=LabelEncoder()
for column in datos.columns:
    datos[column] = encoder.fit_transform(datos[column])
datos.head()

,type,cap_shape,cap_surface,cap_color,bruises,odor,gill_attachment,gill_spacing,gill_size,gill_color,...,stalk_surface_below_ring,stalk_color_above_ring,stalk_color_below_ring,veil_type,veil_color,ring_number,ring_type,spore_print_color,population,habitat
0,1,2,3,0,1,7,1,0,1,0,...,3,7,7,0,2,1,4,0,3,4
1,0,2,3,9,1,0,1,0,0,0,...,3,7,7,0,2,1,4,1,2,0
2,0,0,3,8,1,1,1,0,0,1,...,3,7,7,0,2,1,4,1,2,2
3,1,2,2,8,1,7,1,0,1,1,...,3,7,7,0,2,1,4,0,3,4
4,0,2,3,3,0,6,1,1,0,0,...,3,7,7,0,2,1,0,1,0,0

In [6]:

# se definen los intervalos para los cuartiles
perc =[.25, .50, .75, 1]


# visualizando los datos con describe
desc = datos.describe(percentiles = perc, include='int')

desc

,type,cap_shape,cap_surface,cap_color,bruises,odor,gill_attachment,gill_spacing,gill_size,gill_color,...,stalk_surface_below_ring,stalk_color_above_ring,stalk_color_below_ring,veil_type,veil_color,ring_number,ring_type,spore_print_color,population,habitat
count,8124.000000,8124.000000,8124.000000,8124.000000,8124.000000,8124.000000,8124.000000,8124.000000,8124.000000,8124.000000,...,8124.000000,8124.000000,8124.000000,8124.0,8124.000000,8124.000000,8124.000000,8124.000000,8124.000000,8124.000000
mean,0.482029,2.491876,1.742984,4.323486,0.415559,4.788282,0.974151,0.161497,0.309207,4.729444,...,2.424914,5.446578,5.393402,0.0,1.965534,1.069424,2.291974,3.062038,3.644018,3.221073
std,0.499708,0.901287,1.179629,3.444391,0.492848,1.983678,0.158695,0.368011,0.462195,3.342402,...,0.870347,2.143900,2.194604,0.0,0.242669,0.271064,1.801672,2.825308,1.252082,2.530692
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,2.000000,0.000000,0.000000,0.000000,4.000000,1.000000,0.000000,0.000000,2.000000,...,2.000000,5.000000,5.000000,0.0,2.000000,1.000000,0.000000,1.000000,3.000000,0.000000
50%,0.000000,2.000000,2.000000,3.000000,0.000000,6.000000,1.000000,0.000000,0.000000,4.000000,...,3.000000,7.000000,7.000000,0.0,2.000000,1.000000,2.000000,3.000000,4.000000,3.000000
75%,1.000000,3.000000,3.000000,8.000000,1.000000,6.000000,1.000000,0.000000,1.000000,7.000000,...,3.000000,7.000000,7.000000,0.0,2.000000,1.000000,4.000000,7.000000,4.000000,6.000000
100%,1.000000,5.000000,3.000000,9.000000,1.000000,8.000000,1.000000,1.000000,1.000000,11.000000,...,3.000000,8.000000,8.000000,0.0,3.000000,2.000000,4.000000,8.000000,5.000000,6.000000
max,1.000000,5.000000,3.000000,9.000000,1.000000,8.000000,1.000000,1.000000,1.000000,11.000000,...,3.000000,8.000000,8.000000,0.0,3.000000,2.000000,4.000000,8.000000,5.000000,6.000000

Igual que cuando hicimos el ejemplo con R, vemos que hay una columna que tiene solamente un valor. La eliminamos.

In [8]:
datos.drop(columns=['veil_type'], axis=1, inplace=True)
datos

,type,cap_shape,cap_surface,cap_color,bruises,odor,gill_attachment,gill_spacing,gill_size,gill_color,...,stalk_surface_above_ring,stalk_surface_below_ring,stalk_color_above_ring,stalk_color_below_ring,veil_color,ring_number,ring_type,spore_print_color,population,habitat
0,1,2,3,0,1,7,1,0,1,0,...,3,3,7,7,2,1,4,0,3,4
1,0,2,3,9,1,0,1,0,0,0,...,3,3,7,7,2,1,4,1,2,0
2,0,0,3,8,1,1,1,0,0,1,...,3,3,7,7,2,1,4,1,2,2
3,1,2,2,8,1,7,1,0,1,1,...,3,3,7,7,2,1,4,0,3,4
4,0,2,3,3,0,6,1,1,0,0,...,3,3,7,7,2,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8119,0,4,3,0,0,6,0,0,0,11,...,3,3,4,4,1,1,4,2,1,1
8120,0,2,3,0,0,6,0,0,0,11,...,3,3,4,4,0,1,4,2,4,1
8121,0,3,3,0,0,6,0,0,0,1,...,3,3,4,4,1,1,4,2,1,1
8122,1,4,2,0,0,3,1,0,1,2,...,3,2,7,7,2,1,0,7,4,1
8123,0,2,3,0,0,6,0,0,0,11,...,3,3,4,4,1,1,4,5,1,1

Ahora hay que crear los juegos de entrenamiento y prueba, hay una función para eso

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(datos.drop(columns=['type']), datos['type'], test_size=0.33, random_state=42)

In [11]:
X_train.head()

,cap_shape,cap_surface,cap_color,bruises,odor,gill_attachment,gill_spacing,gill_size,gill_color,stalk_shape,...,stalk_surface_above_ring,stalk_surface_below_ring,stalk_color_above_ring,stalk_color_below_ring,veil_color,ring_number,ring_type,spore_print_color,population,habitat
3244,3,0,7,1,6,1,0,0,1,1,...,3,3,5,3,2,1,4,0,5,6
3739,2,0,3,0,2,1,1,1,7,0,...,3,3,7,7,2,1,4,0,4,6
2154,2,0,7,1,6,1,0,0,1,1,...,3,3,7,3,2,1,4,1,5,6
1344,3,3,8,0,6,1,1,0,1,1,...,3,3,7,7,2,1,0,1,3,0
7852,4,2,0,0,8,1,0,1,2,1,...,3,2,7,7,2,1,0,7,4,1

Se crea un objeto con el clasificador y con el método **fit** se ajusta el modelo con los datos de entrenamiento

In [15]:
clf = DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)

A partir del modelo y el método **predict** se crean los valores predichos por el modelo con los datos de prueba, el resultado se asigna a X_pred.

In [17]:
y_pred=clf.predict(X_test)

In [19]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
print(f"Precisión del modelo: {accuracy:.2f}")

Precisión del modelo: 1.00

Examinamos los valores de cada uno

In [21]:
y_pred

array([0, 1, 1, ..., 0, 0, 0])

In [ ]:
X_test

Generando la matriz de confusion

In [22]:
from sklearn.metrics import classification_report, confusion_matrix
cfm=confusion_matrix(y_test, y_pred)
cfm

array([[1378,    0],
       [   0, 1303]])